In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
df.shape

(569, 31)

**Trai Test Split**

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

**Scaling**


In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 0.12614807, -0.54213486,  0.07497327, ..., -0.56812608,
        -0.70505695, -0.99336558],
       [ 0.86715263,  0.67709002,  0.89429501, ...,  0.57117693,
         0.28077376, -0.50625702],
       [-0.15347629, -0.6599009 , -0.20909073, ..., -0.45223884,
        -0.88063791, -0.20949381],
       ...,
       [-1.36844413, -1.22333057, -1.3149113 , ..., -0.65465929,
         1.26982615,  0.3154644 ],
       [ 0.54558461, -1.00165332,  0.48443124, ..., -0.03883635,
        -0.18475741, -0.76517058],
       [-1.23981692,  2.0787368 , -1.24511271, ..., -1.02097303,
        -0.92090877, -0.65600999]])

In [10]:
y_train

486    B
262    M
51     B
532    B
206    B
      ..
525    B
114    B
520    B
406    B
459    B
Name: diagnosis, Length: 455, dtype: object

**Label Encoding**

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,

**Numpy arrays to Pytorch tensors**

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [16]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    #Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

**Important Parameters***

In [17]:
learning_rate = 0.1
epochs = 25

**Training Pipeline**

In [18]:
#create model
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model.forward(X_train_tensor)

  #loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.4589142589328707
Epoch: 1, Loss: 3.4589142589328707
Epoch: 2, Loss: 3.3313628400856747
Epoch: 2, Loss: 3.3313628400856747
Epoch: 3, Loss: 3.1949233158287895
Epoch: 3, Loss: 3.1949233158287895
Epoch: 4, Loss: 3.0569842499096245
Epoch: 4, Loss: 3.0569842499096245
Epoch: 5, Loss: 2.917336983299882
Epoch: 5, Loss: 2.917336983299882
Epoch: 6, Loss: 2.772954238078923
Epoch: 6, Loss: 2.772954238078923
Epoch: 7, Loss: 2.622769638919618
Epoch: 7, Loss: 2.622769638919618
Epoch: 8, Loss: 2.4730709512104228
Epoch: 8, Loss: 2.4730709512104228
Epoch: 9, Loss: 2.3174406793383167
Epoch: 9, Loss: 2.3174406793383167
Epoch: 10, Loss: 2.162557964301186
Epoch: 10, Loss: 2.162557964301186
Epoch: 11, Loss: 2.011680543970971
Epoch: 11, Loss: 2.011680543970971
Epoch: 12, Loss: 1.8650384239206643
Epoch: 12, Loss: 1.8650384239206643
Epoch: 13, Loss: 1.7238960264600343
Epoch: 13, Loss: 1.7238960264600343
Epoch: 14, Loss: 1.5876047806495492
Epoch: 14, Loss: 1.5876047806495492
Epoch: 15, Loss: 1.4

In [19]:
model.bias

tensor([-0.1409], dtype=torch.float64, requires_grad=True)

**Evaluatin**

In [20]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6108033061027527


**Defining the model by compressing and reducing the size of the code**

In [21]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  def loss_function(self, y_pred, y):
    #Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    #Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

**Important Parameters***

In [22]:
learning_rate = 0.1
epochs = 25

**Training Pipeline**

In [23]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor.float())

  #loss calculate
  loss = model.loss_function(y_pred, y_train_tensor.float())
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7614601254463196
Epoch: 1, Loss: 0.7614601254463196
Epoch: 2, Loss: 0.7436370253562927
Epoch: 2, Loss: 0.7436370253562927
Epoch: 3, Loss: 0.7316399216651917
Epoch: 3, Loss: 0.7316399216651917
Epoch: 4, Loss: 0.7231679558753967
Epoch: 4, Loss: 0.7231679558753967
Epoch: 5, Loss: 0.7168232202529907
Epoch: 5, Loss: 0.7168232202529907
Epoch: 6, Loss: 0.7118047475814819
Epoch: 6, Loss: 0.7118047475814819
Epoch: 7, Loss: 0.707659900188446
Epoch: 7, Loss: 0.707659900188446
Epoch: 8, Loss: 0.7041282057762146
Epoch: 8, Loss: 0.7041282057762146
Epoch: 9, Loss: 0.7010531425476074
Epoch: 9, Loss: 0.7010531425476074
Epoch: 10, Loss: 0.6983348727226257
Epoch: 10, Loss: 0.6983348727226257
Epoch: 11, Loss: 0.6959056854248047
Epoch: 11, Loss: 0.6959056854248047
Epoch: 12, Loss: 0.6937166452407837
Epoch: 12, Loss: 0.6937166452407837
Epoch: 13, Loss: 0.6917309165000916
Epoch: 13, Loss: 0.6917309165000916
Epoch: 14, Loss: 0.6899194121360779
Epoch: 14, Loss: 0.6899194121360779
Epoch: 15, L

In [24]:
model.linear.weight

Parameter containing:
tensor([[-0.0163,  0.1273,  0.0264, -0.0121, -0.0304, -0.0921,  0.0566,  0.0550,
          0.1058, -0.0338, -0.0599,  0.0706,  0.0389, -0.1256, -0.0719,  0.0168,
          0.0822,  0.0128,  0.0372, -0.0144, -0.1539, -0.1391,  0.0845,  0.0775,
          0.0883,  0.0146, -0.1038,  0.1040, -0.1324, -0.0323]],
       requires_grad=True)

**Evaluating**

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6315789222717285


**Modifying code by building our own loss function**

In [26]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out


**Important Parameters***

In [27]:
learning_rate = 0.1
epochs = 25

In [28]:
loss_function = nn.BCELoss()  #BCE - Binary Cross Entropy

**Training Pipeline**

In [29]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor.float())

  #loss calculate
  loss = loss_function(y_pred, y_train_tensor.float().view(-1, 1))

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.5617265701293945
Epoch: 2, Loss: 0.4589715600013733
Epoch: 3, Loss: 0.3973431885242462
Epoch: 4, Loss: 0.3556225597858429
Epoch: 5, Loss: 0.325114369392395
Epoch: 6, Loss: 0.3016260266304016
Epoch: 7, Loss: 0.2828610837459564
Epoch: 8, Loss: 0.2674456536769867
Epoch: 9, Loss: 0.25450319051742554
Epoch: 10, Loss: 0.24344557523727417
Epoch: 11, Loss: 0.23386254906654358
Epoch: 12, Loss: 0.22545811533927917
Epoch: 13, Loss: 0.21801280975341797
Epoch: 14, Loss: 0.21136042475700378
Epoch: 15, Loss: 0.20537202060222626
Epoch: 16, Loss: 0.19994626939296722
Epoch: 17, Loss: 0.19500206410884857
Epoch: 18, Loss: 0.19047372043132782
Epoch: 19, Loss: 0.1863073855638504
Epoch: 20, Loss: 0.18245838582515717
Epoch: 21, Loss: 0.17888936400413513
Epoch: 22, Loss: 0.17556877434253693
Epoch: 23, Loss: 0.17246980965137482
Epoch: 24, Loss: 0.1695694774389267
Epoch: 25, Loss: 0.16684801876544952


In [30]:
model.linear.weight

Parameter containing:
tensor([[ 0.4031,  0.2149,  0.4047,  0.2300,  0.1696,  0.0440,  0.2302,  0.2575,
          0.1719,  0.0588,  0.1714, -0.0439,  0.0915,  0.1709, -0.0249,  0.0102,
         -0.0186, -0.0973,  0.0423, -0.1184,  0.1480,  0.2961,  0.3040,  0.2271,
          0.0253,  0.1275,  0.3055,  0.1060,  0.2425,  0.1867]],
       requires_grad=True)

**Evaluatin**

In [31]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5369344353675842


**Modifying code by using the optimizer SGD**

In [38]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out


**Important Parameters***

In [39]:
learning_rate = 0.1
epochs = 25

In [40]:
#defining loss function
loss_function = nn.BCELoss()  #BCE - Binary Cross Entropy

**Training Pipeline**

In [41]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor.float())

  #loss calculate
  loss = loss_function(y_pred, y_train_tensor.float().view(-1, 1))

  #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

   # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8800602555274963
Epoch: 2, Loss: 0.6210423111915588
Epoch: 3, Loss: 0.485059529542923
Epoch: 4, Loss: 0.41029688715934753
Epoch: 5, Loss: 0.3632294237613678
Epoch: 6, Loss: 0.3303106427192688
Epoch: 7, Loss: 0.3056086599826813
Epoch: 8, Loss: 0.2861674129962921
Epoch: 9, Loss: 0.2703384757041931
Epoch: 10, Loss: 0.2571198046207428
Epoch: 11, Loss: 0.2458617389202118
Epoch: 12, Loss: 0.23612146079540253
Epoch: 13, Loss: 0.2275853306055069
Epoch: 14, Loss: 0.22002403438091278
Epoch: 15, Loss: 0.21326537430286407
Epoch: 16, Loss: 0.20717716217041016
Epoch: 17, Loss: 0.20165608823299408
Epoch: 18, Loss: 0.196619912981987
Epoch: 19, Loss: 0.1920023262500763
Epoch: 20, Loss: 0.18774917721748352
Epoch: 21, Loss: 0.1838156282901764
Epoch: 22, Loss: 0.18016424775123596
Epoch: 23, Loss: 0.17676353454589844
Epoch: 24, Loss: 0.17358669638633728
Epoch: 25, Loss: 0.17061080038547516


In [36]:
model.linear.weight

**Evaluatin**

In [42]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5346260666847229
